### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by CleoMenezesJr** [LimaJonas/chat-curriculum#1]
Fala, mano! Da hora teu projeto. Faz um github pages dele. ;)

**Comment by LimaJonas** [comment]
Opa, boa tarde,

Eu já tinha colocado no git pages mas tinha esquecido de colocar o link no
projeto. Mas muito obrigado por ke lembrar.

Segue o link https://limajonas.github.io/chat-curriculum/

Em ter, 26 de jan de 2021 19:59, Cleo Menezes <notifications@github.com>
escreveu:
