### ISSUE TITLE
Suggestion : Messages bot 

### ISSUE THREAD

**Issue by seon22break** [LimaJonas/chat-curriculum#2]
¡ Hi ! , Your idea is very good,  I dont know portuguese, but I have a suggestion for chatbot. 

The messages sent by the bot should be saved in a json. A JSON for each language would allow your idea to be run around the world. If you approve this suggestion I will help you translate into Spanish.

Good Work !!

Thanks!!

**Comment by LimaJonas** [comment]
Good idea! 

Thanks for the sugestion. I'm a little busy right now. But I will do that soon.

**Comment by LimaJonas** [comment]
Done!
